### ISSUE TITLE
Specify in the docs how keys are matched

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/registry#3]
I think is a good idea to specify in the docs how keys are matched in lookup/dispatch.
(I had to dig into the sources to find out)

Basically being :ets.lookup the search key must "compare equal to" is the Registry is unique,
otherwise the key "matches" if duplicates are allowed.

This is nice since allows to do a more complex PubSub topic dispatch since you can match different things.

For example, a process is registered with the key %{country: "IT", weather: "Rome"} and another with %{country: "IT", weather: "Milan"} and I can lookup processes which handle weather in Italy with %{country: "IT", weather: city} 

Unfortunately my english is not very good, otherwise I'll be glad to submit a PR for the doc.

**Comment by josevalim** [comment]
> For example, a process is registered with the key %{country: "IT", weather: "Rome"} and another with %{country: "IT", weather: "Milan"} and I can lookup processes which handle weather in Italy with %{country: "IT", weather: city}

This is actually not possible. The distinction between match and equal is regarding the use of `===` (match) and `==` (equal) operators.

In any case, this is a great suggestion, I will update the docs!

**Comment by josevalim** [comment]
Done. Btw, all types in the registry use the match operator `===`.

**Comment by xadhoom** [comment]
ok thanks! 
got it, still a lot to learn :) 

(btw doing a sort of pattern matching on keys can be a great addition, like amqp does, but for local processes)

**Comment by xadhoom** [comment]
For example, using :ets.select is possible:
(using also ex2ms to easily build match_spec funs)

```
table = :ets.new(:buckets_registry, [:set, :protected])
:ets.insert(table, {%{c: "it", wt: "milan"}, "milan w"})
:ets.insert(table, {%{c: "it", wt: "rome"}, "rome w"})

filt = fun do y = {%{wt: x}, _} when x == "rome" -> y end
:ets.select(table, filt)                                 
[{%{c: "it", wt: "rome"}, "rome w"}
```

maybe (in the future) add some sort of support for this kind of matches.
